### ISSUE TITLE
Compile on Debian Jessie fix

### ISSUE THREAD

**Issue by kwadroke** [abandonware/pinedit#1]
In order to compile on Debian Jessie, you need to add the following to src/polygonview.cpp (I added it to line 51)
`#include <stdint.h>`

Dependancies required to compile (modified from /debian/control) :
`libtool libltdl-dev libqt4-dev autoconf automake libtool sp sgmlspl docbook docbook-utils libltdl-dev  libgl1-mesa-dev freeglut3-dev libsdl1.2-dev libsdl-image1.2-dev libpng-dev libtiff5-dev libaa1-dev libsdl-mixer1.2-dev libogg-dev libvorbis-dev libasound2-dev`

**Comment by sergiomb2** [comment]
Hi , are you testing git HEAD , i.e. qt4 support ? 
A pull request is more than welcome

**Comment by moleculext** [comment]
Hi,
I've succeeded to build the deb package with branch https://github.com/moleculext/pinball-pinedit/tree/fix_qpainter on Debian Stretch (current Debian Stable).

I had to remove the following dependencies in debian/control file:
`libqt3-mt-dev, libqt3-compat-headers` and `libtiff4-dev` and type `autoreconf -vif`before launching `debuild -us -uc -b`

Lots of auto-generated files should be removed from git scm, as suggested in the pull request https://github.com/sergiomb2/pinball-pinedit/pull/3

I hope this helps.

**Comment by sergiomb2** [comment]
Hi, First many thanks for your efforts  , 
we may fix  debian folder on this project , why not ? 
Also I may give you commit rights to this project if you want or like it

**Comment by sergiomb2** [comment]
@moleculext 
> I had to remove the following dependencies in debian/control file:
libqt3-mt-dev, libqt3-compat-headers and libtiff4-dev and type autoreconf -vifbefore launching debuild -us -uc -b

could you please do a commit and a pull request with this changes in debian directory ? thanks

**Comment by sergiomb2** [comment]
I would appreciate a lot, I may move all sources to https://github.com/sergiomb2/pinball.  if it is working ... 

Many thanks
