### ISSUE TITLE
Status of pinedit ?

### ISSUE THREAD

**Issue by rzr** [abandonware/pinedit#6]
Hi i was wondering who is maintaining pinedit ?
is it @abandonware ?

Relate-to: https://github.com/rzr/pinball/issues/13

**Comment by sergiomb2** [comment]
please look at https://github.com/sergiomb2/pinball-pinedit/commits/master 
Commits on May 1, 2011 was you , after I merged qt4 branch and after we got a few commits from @moleculext , TBH I almost not test it and even I'm not sure that source compiles  .

Conclusion, the code is abandoned

**Comment by rzr** [comment]
ok then tell me if it can be relocated to https://github.com/abandonware 

you need to do this at bottom of project settings page:
https://github.com/sergiomb2/pinball-pinedit/settings

**Comment by sergiomb2** [comment]
Transfer ownership ? I don't see any relocated option

**Comment by rzr** [comment]
yes in "transfer ownership" section there is a "transfer" button on right

then you need to set new owner : "abandonware"
and confirm by typing "sergiomb2/pinball-pinedit"

Then https://github.com/sergiomb2/pinball-pinedit will redirect to the new place

**Comment by sergiomb2** [comment]
You don’t have the permission to create public repositories on abandonware

**Comment by rzr** [comment]
Haven't you recieved my invitation to join @abandonware org

I see your name pending at:

https://github.com/orgs/abandonware/people/pending_invitations

**Comment by sergiomb2** [comment]
OK

**Comment by sergiomb2** [comment]
done

**Comment by rzr** [comment]
thx a lot welcome to the raft :)
